### ISSUE TITLE
Is the plan that freebsd/iocage take over from iocage/iocage

### ISSUE THREAD

**Issue by madu41** [freebsd/iocage#14]
iocage in FreeBSD is based on https://github.com/iocage/iocage which is dead. My 13.2 jails cannot be updated to 13.3. It fails with etcupdate.

This repository is the base of iocage-devel in FreeBSD, but no packages are built on that, as far as I can see. What are the plans? Should we hope that iocage can continue? Or should we look for a replacement?

Specifically, is my issue of upgrade known to others? If so, is it solved in iocage-devel?

**Comment by dgeo** [comment]
Hi,
I'm not the port maintainer but here is a pr to update sysutils/iocage: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269298
@arrowd did fork this here and we are currently maintaining this.

**Comment by arrowd** [comment]
`iocage-devel` is an upgrade of `iocage` that takes distfiles from this repo and works with Python 3.11.

There is some uncertainty if it is ready to replace `iocage`: https://lists.freebsd.org/archives/dev-commits-ports-main/2024-June/110275.html

I think, I'll try it our myself first and then we can switch the `iocage` port to this repo too and remove `iocage-devel` altogether.

**Comment by madu41** [comment]
Thanks for the clarifications. If this project lifts I might be able to contribute to it in some form.

Right now I have to solve my issue where `iocage/iocage` won't upgrade jails with 13.2-p12 to 13.3 that the host has been upgraded to.

**Comment by arrowd** [comment]
You can contribute already by switching to `iocage-devel` to see if the bug is still present.

**Comment by dgeo** [comment]
That said, I resolved all bugs I saw here while testing but may have missed some on different setups...

**Comment by dgeo** [comment]
@arrowd Now I'm running 1.7 for weeks, I upgraded 200+ jails on 1213.3/14.1 hosts with different configs, python 3.9 and 3.11, and jails (vnet and not) from 11.4 to 14.1. I did not hit any bug.

**Comment by arrowd** [comment]
I finally managed to do some smoke testing of `iocage-devel` and it seems to work fine for my tasks.

The only thing that I spotted is that `iocage stop foo` results in

```
  + Removing jail process FAILED:
jail: the 'allow.dying' parameter and '-d' flag are deprecated and have no effect.
```

although the jail gets stopped successfully.

I think we can now switch the main iocage port to this version. When we do this, should we remove `iocage-devel` altogether?

**Comment by arrowd** [comment]
I started updating the port and noticed that it pulls additional patches that aren't present in this repository:

https://github.com/iocage/iocage/commit/2883770ae46731a2a94cd41e6d01d32cec6f1f21.patch
https://github.com/iocage/iocage/commit/753b2f35731423597d7f51f33427b6d619fcd0b5.patch
https://github.com/iocage/iocage/commit/b47dc2c47ff125d644720b03f598a9caf4e08192.patch
https://github.com/iocage/iocage/commit/2a1685bcaba96917c79a7e4a909dac5c6926826a.patch
https://github.com/iocage/iocage/commit/c06d0695487dda62c2b81aeb6be5fe91a70d8c83.patch

@dgeo Can you please check if these are required and if yes - make a new release containing these fixes?

**Comment by dgeo** [comment]
I did this work before the patch I proposed here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269298 (with 1.3, and some corrections later)
I use this patch to sysutils/iocage port here for our poudriere since then.
As stated in the git commit message integrated in the patch, all port's patches have been integrated before.

Yours
Geoffroy

**Comment by arrowd** [comment]
The `sysutils/iocage` port now targets the 1.8 release from this repo.
