### ISSUE TITLE
Samba-4.19 cannot mount fdescfs in a iocage managed jail running freebsd-14.1

### ISSUE THREAD

**Issue by byrnejb** [freebsd/iocage#15]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [✔ ] Supply `iocage --version`   Version 1.2

- [ ✔] Supply the commands used, along with any steps to recreate it.
       # service samba_server start

- [✔ ] Provide the output from the command you issued.
Performing sanity check on Samba configuration: OK
/usr/local/etc/rc.d/samba_server: WARNING: samba_server: cannot fdescfs mount to /var/run/samba4/fd

- [ ✔] Supply what you expected the result or output to be
Samba-4.19  starts without warnings or errors.

- [ ✔] Checked that the problem has not already been fixed on `master` if using
 a stable release.
None found

Issue appears to be caused by iocage inability to set  jail specific permissions for `sysctls security.jail.mount_fdescfs_allowed` and `security.jail.param.allow.mount.fdescfs`.  These have been deprecated in favour of per-jail options.  Adding these settings to iocage possibly may resolve this issue.

Also consider providing iocage with a generic method of manually adding settings not handled by the existing set command options.

**Comment by byrnejb** [comment]
Already fixed.

**Comment by dgeo** [comment]
I added support for this here: https://github.com/freebsd/iocage/commit/7c1fe5a02200bf03b8b518fcca62e97abb8b58a8
