### ISSUE TITLE
Enhancement For The Snapshot Command To List Snapshots

### ISSUE THREAD

**Issue by okalm** [freebsd/iocage#16]
Hi,

It would be nice to have the possibility to handle snapshots totally from `iocage` so we could create, list and rollback snapshots from `iocage` only. 
Currently we have to switch between `ZFS` and `iocage` commands for this operation.

Instead we could have something like this:
-## create a snapshot
`$ iocage snapshot --name before_changes myjail`
-## list the snapshots
`$ iocage snapshot --list`
-## do a rollback
`$ iocage rollback myjail@before_changes`

Currently in order to list the snapshots of `iocage` only I do this:
`$ zfs list -t snapshot -o name | grep iocage |  awk -F'/' '{print $NF}'`
`$ myjail@before_changes`

The absolute path is removed leaving only the name of the snapshot.
"iocage" passed to grep is the name of the dataset, I think it's the default so it should be okay for everyone?

Unfortunately I don't code so I can't help to convert this in python more than I did.
What do you think, is it possible to add this option?

Thank you.

**Comment by dgeo** [comment]
Hi @okalm,

I think you can already:
```
$ iocage snapshot -n mysnap1 myjail
$ iocage snaplist myjail
$ iocage rollback -n mysnap1 myjail
```
for scripting, use ``iocage snaplist -h`` or ``iocage snaplist -hl``

Please tell me what I miss here on your use-case

**Comment by dgeo** [comment]
you're welcome.
I'd also prefer a single sub-command "snapshot", but for now I prefer keeping il running as before...
