### ISSUE TITLE
snapremove ALL does not work

### ISSUE THREAD

**Issue by DaLynX** [freebsd/iocage#18]
Version: 1.6

Commands used: iocage snapremove jailname ALL / snapremove ALL jailname
Output: usage message

Commands used: iocage snapremove jailname -n ALL
Output: Snapshot /iocage/path/to/jail@ALL not found!

See https://github.com/iocage/iocage/issues/1098

**Comment by dgeo** [comment]
I think this rever worked, though I didn't double-checked (no real keyboard with me to do that)
I take this for a future enhancement

**Comment by DaLynX** [comment]
Yes it's totally absent from the code, you're right. 
Would you be interested in a PR? I think it could be implement easily at the cli level, not necessarily touching the lib part.

The only question I see is do we want to support ALL as a jail target as well (remove a specifically named snapshot from all jails, or all snapshots from all jails)?

**Comment by dgeo** [comment]
good questions...
I suppose it would need at least --force or interactive confirmation in both case to avoid errors, and recursion checks for clones elsewhere ?
For ALL jails, it should be consistent with other commands.
And yes, ar PR would be nice !

Yours,
Geoffroy

**Comment by Defenso-QTH** [comment]
Hello,

I am having a look at this and wondering: wouldn't removing the oldest snapshot automatically remove all the following ones anyway?

**Comment by Defenso-QTH** [comment]
@dgeo FYI I have been working on this, I will do some cleanup and propose a PR before the end of the week.
