### ISSUE TITLE
iocage pkg install doesn't show all the output, so it hangs

### ISSUE THREAD

**Issue by okalm** [freebsd/iocage#19]
The command `iocage pkg` hangs when `install` is passed to it.

```
root@myhost: iocage pkg testjail install vim
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
^C
Aborted!
```

Normally `pkg` shows some text and at the end it asks the user to confirm the installation with a prompt [y/n], currently that part of the text is missing.
To bypass this issue we can use `install -y` to make it work, or blindly press [y] then [enter].
To be sure I also tested with the other package `systutils/iocage` and it does the same thing (hmm I've just found that it is [already reported here](https://github.com/iocage/iocage/issues/1056
))

Tested on:  FreeBSD 14.1-RELEASE-p3	
Iocage : Version 1.7

**Comment by Defenso-QTH** [comment]
@dgeo easy merge here if you have a minute.
