### ISSUE TITLE
Latest docs page is for older version

### ISSUE THREAD

**Issue by evanjrowley** [freebsd/iocage#35]
The current release of iocage is 1.8 but the "latest" documentation is still 1.2. How does one access the updated documentation?

**Comment by Defenso-QTH** [comment]
Docs you found are not from this repo but from https://github.com/iocage/iocage.

AFAIK there is no automatic building and publishing of docs on this repo, yet. So you have to build the docs yourself or browse the source.

@dgeo maybe if you look into setting up CI this could be addressed at the same time?

**Comment by Defenso-QTH** [comment]
This is even more urgent now that the port points to this repo (see #14).

**Comment by dgeo** [comment]
you're right, I still have to look at this.
I tried to contact former authors to take over readthedocs's current iocage doc, but without luck...
