### ISSUE TITLE
iocage-fetch loses some release permissions

### ISSUE THREAD

**Issue by rookiejet** [freebsd/iocage#54]
`iocage fetch` loses some permissions on untar of release archives, e.g. world write on `/tmp` and `/var/tmp`, group write on `/var/mail` and `/var/spool/dma`, possibly related to this: https://github.com/freebsd/iocage/pull/49

This is using iocage-1.8_1 from ports which pulls in this patch as well in: https://github.com/freebsd/freebsd-ports/commit/c4139815d8f3472317e6461da7f2589cc5a7ccbf

iocage-1.8 doesn't exhibit this behavior.

Is this intentional?

**Comment by dgeo** [comment]
Of course not !
I didin't check enought this patch... nor do I understand well what tar_filter is exactly... I'll try to look closely ASAP, but if anyone have clues I'll take it !

**Comment by dgeo** [comment]
@grembo any thougths ?

**Comment by grembo** [comment]
@dgeo Looking into it. Seems like the tarfilter chosen by TrueNAS is too strict (tarfilters can be customized though, so there should be a way to correct this without reverting everything).

**Comment by grembo** [comment]
@dgeo Did a fix and tested it locally. Depending on how long testing/creating a new release takes, I would either patch the port or wait for a new official release. I'll also let the TrueNAS folks know.

**Comment by dgeo** [comment]
I can make a release quickly (tomorrow) to fix that...

**Comment by grembo** [comment]
Ok, cool. I pushed a patch to the ports (iocage and iocage-devel) in the meantime, so I could cherry-pick the fix to the 2024Q4 branch. Once the new release is ready, I will update devel/iocage to the new version number and remove the patches.

**Comment by rookiejet** [comment]
I've tested the fix some locally and it seems to be working as expected. Thanks for your quick attention to this. Please close or keep open this issue as you see fit.
